name: Capture

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    # triggers the workflow every 60 minutes
    - cron:  '*/60 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install Dep
      uses: ianwalter/puppeteer@3.0.2
      with:
        args: yarn

    - name: Capture Screenshots
      uses: ianwalter/puppeteer@3.0.2
      with:
        args: yarn capture

    - name: Save screenshots
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Bot
        author_email: huanghuanshds@gmail.com
        message: "Save screenshots"
        add: "*.jpeg"

    - name: Update data.json
      uses: EndBug/add-and-commit@v4
      with:
        author_name: Bot
        author_email: huanghuanshds@gmail.com
        message: "Update data.json"
        add: "data.json"
